import Head from 'next/head';
import Header from './components/Header';
import { Container, Box } from '@mui/material';
import { useStateContext } from './context/ContextProvider';
import SearchBar from './components/SearchBar';
import FilterRegion from './components/FilterRegion';

// sx={{ color: currentMode === 'light' ? 'red' : 'green' }}
export default function Home() {
  const { currentMode } = useStateContext();

  return (
    <div>
      <Head>
        <title>Where in the world?</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <Box
          sx={{
            height: '100vh',
            bgcolor:
              currentMode === 'light'
                ? 'lightModeBackground.main'
                : 'darkModeBackground.main',
          }}
        >
          <Container>
            <SearchBar />
            <Box mt={5}>
              <FilterRegion />
            </Box>
          </Container>
        </Box>
      </main>
    </div>
  );
}
